services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
    depends_on:
      - db
    stdin_open: true
    tty: true

  tailwind:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: |
      sh -c '
        set -e
        echo "🎨 Iniciando Tailwind CSS..."
        mkdir -p app/assets/builds # Garante que o diretório exista
        echo "📦 Executando build inicial do Tailwind CSS..."
        bundle exec rails tailwindcss:build
        echo "✅ Build inicial concluído."
        echo "👀 Iniciando Tailwind CSS em modo watch..."
        bundle exec rails tailwindcss:watch # Comando otimizado e mais silencioso
      '
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle # Shares same cache as gems
    depends_on:
      - app
    environment:
      - RAILS_ENV=development
    stdin_open: true
    tty: true
    restart: unless-stopped


  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=app_development
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  bundle_cache: