services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/up || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    stdin_open: true
    tty: true
    restart: unless-stopped

  tailwind:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: |
      sh -c '
        set -e
        echo "🎨 Iniciando Tailwind CSS..."
        mkdir -p app/assets/builds # Garante que o diretório exista
        echo "📦 Executando build inicial do Tailwind CSS..."
        bundle exec rails tailwindcss:build
        echo "✅ Build inicial concluído."
        echo "👀 Iniciando Tailwind CSS em modo watch..."
        bundle exec rails tailwindcss:watch # Comando otimizado e mais silencioso
      '
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle # Shares same cache as gems
    depends_on:
      app:
        condition: service_healthy
    environment:
      - RAILS_ENV=development
    stdin_open: true
    tty: true
    restart: unless-stopped

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=app_development
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
  bundle_cache: