default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %> # Usará 'db' de Docker Compose
  username: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } %> # Usará 'postgres' de Docker Compose
  password: <%= ENV["POSTGRES_PASSWORD"] %> # Usará 'postgres_password' de Docker Compose

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "app_development" } %>

test:
  <<: *default
  database: app_test # Você pode configurar um POSTGRES_DB_TEST se quiser

# Ajuste a configuração de produção conforme necessário,
# ela não será usada por este docker-compose de desenvolvimento.
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> # Exemplo, se você usar DATABASE_URL em produção