default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %> # Uses 'db' from Docker Compose
  username: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } %> # Uses 'postgres' from Docker Compose
  password: <%= ENV["POSTGRES_PASSWORD"] %> # Uses 'postgres_password' from Docker Compose

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "app_development" } %>

test:
  <<: *default
  database: app_test # It's possible to config a POSTGRES_DB_TEST

# Adjust production config as needed,
# wont't be used by docker-compose in development.
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> # Ex, if you use DATABASE_URL in production